### ISSUE TITLE
Trouble installing requirements.txt

### ISSUE THREAD

**Issue by jac111** [halaelnahal/bme590final#12]
I'm getting an error when trying the command: pip install -r requirements.txt
error: Collecting python==3.6 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement python==3.6 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for python==3.6 (from -r requirements.txt (line 3))

I looked over other requirements.txt files we've created and we chose to omit a python requirement... Am I making a silly mistake here (due to my foggyness on doing this)? Or can we setup the virtual environment without specifying the python version in requirements.txt?

**Comment by mlp6** [comment]
You do not want to specify a python version when using `pip`; `pip` will install python packages for the python version that is installed and activated.  If you have multiple versions of python installed on a system, then you would want to activate the appropriate one when creating your `virtualenv`.  @suyashkumar had a tutorial on this setup here: https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/lecture04/pip-and-conda-install.md

Confusingly, `conda` works a bit differently, and you can pull in a python version <= to the one you are using in those environments... but the syntax in an `environment.yml` file does not directly translate over to a `requirements.txt` file.

**Comment by jac111** [comment]
Thank you! Very helpful.
