### ISSUE TITLE
trouble with Docker on VM

### ISSUE THREAD

**Issue by jac111** [halaelnahal/bme590final#16]
I've gotten my server running locally on my computer and now I am trying to replicate this functionality on my VM. I've downloaded docker and was able to run "sudo docker run hello-world" so it appears to be functional but when I try "docker-compose up --build" I get the following error:

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

I've done some googling and I'm stuck! Thanks for your help.

**Comment by mlp6** [comment]
@jac111 since this has been a common problem, I'm going to post this here: https://gitter.im/Duke-BME-Hackers/Software
