### ISSUE TITLE
Different prediction than example given

### ISSUE THREAD

**Issue by jac111** [halaelnahal/bme590final#23]
I fed my route the base 64 string of MALIGNANT_IMAGES[0] from Example get_prediction.ipynb. The result from the Example is

('img type:', <type 'numpy.ndarray'>)
('img shape:', (768, 1024, 3))

Predictions:
['non malignant', 'malignant']
[ 0.34570268  0.65429735]

My code is giving me

{
    "labels": "['non malignant', 'malignant']",
    "predictions": "[ 0.50162625  0.49837369]",
    "shape": "(768, 1024, 3)",
    "type": "<type 'numpy.ndarray'>"
}

Not sure why the prediction is different when it appears I successfully fed get_prediction the same data as in the example.

**Comment by mlp6** [comment]
Is the exactly running the example "as is", or is this using your routines to send the data as `base64`?  If the latter, is there a chance that you have reshaped the `base64` incorrectly after decoding it?  You have the same shape, but if you ordered the string differently, you would get different values mapped to those indices.  Just a guess...

**Comment by jac111** [comment]
Yep, it was a decoding bug! Thanks, Dr. Palmeri
